sugarcube-2:
  macros:
    tooltip:
      name: tooltip
      description: "Show a tooltip when hovering over text\n\nUsage:\n\n```\n<<tooltip \"tooltipText\" [direction]>>triggerText<</tooltip>>\n```\n\nCustom Macro."
      container: true
      parameters:
          - "text |+ (top | bottom | left | right | auto)"
