sugarcube-2:
  macros:
    acts:
      name: acts
      description: Adds action buttons to the page
      parameters:
        - text ...text
    tooltip:
      name: tooltip
      description: |-
        Show a tooltip when hovering over text

        Usage:

        ```
        <<tooltip "tooltipText" [direction]>>triggerText<</tooltip>>
        ```

        Custom Macro.
      container: true
      parameters:
        - text |+ ('top'|'bottom'|'left'|'right'|'auto')
    convo:
      name: convo
      description: |-
        Use Chapel's speech macro to show a conversation box that can be cycled through

        Content inside `<<convo>><</convo>>` will be executed silently when the last line of the conversation is displayed.
        Requires Chapel's speech box and continue macros from: https://twinelab.net/custom-macros-for-sugarcube-2/

        Usage:

        ```
        <<convo [characterName] [(left|right)]>>
            <<line [characterName] [(left|right)]>>line 1
            <<line>>line 2
            <<line>>line 3
            <<convocomplete>>
                <!-- stuff to do when the convo is done -->
        <</convo>> 
        ```

        Arguments:
        
        - characterName: `string` - matches with a character name string provided to <<character>>
        - (left|right) - Which side to place the portrait on. Default left

        Children:
        - `<<line>>` - Required. Each of these will be a line that shows up in the box
        - `<<convocomplete>>` - Optional. Content to run silently after the content is dune.
      container: true
      children: ['lines', 'convocomplete']
      parameters: 
        - text |+ ('left'|'right')
    line:
        name: line
        description: |-
            Line of text to put into a convo
            Each line should be separated by a newline.

            Arguments:
            - characterName: - `string` the character that is speaking. If not provided, will default to the characterName provided in `<<convo>>`
            - (left|right) - Which side to place the portrait on. If not provided, will default to the direction provided in `<<convo>>` (which itself defaults to "left")

            See `<<convo>>` for usage
        parameters:
            - (|+ text |+ ('left'|'right'))
    convocomplete:
        name: convocomplete
        description: |-
            The contents of `<<convocomplete>>` will be run after the convo is complete.
            See `<<convo>>` for usage
    # speech macro characters
    augcomm:
      name: augcomm
      container: true
    pc:
      name: pc
      container: true
    mora:
      name: mora
      container: true
